name = "forgeworks"
author = "Jaron Zijlstra"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7127775c4a6517e7758dff0a48f2e65b2541098672d0d5737496515e0a72e332"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.173"

[options]
acceptable-game-versions = ["1.21.1"]
