name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6e15e426b1fa607f6090bb8ad4db4599863c2b1d0f14ac4abe1aa4745abcbc8"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.173"

[options]
acceptable-game-versions = ["1.21.1"]
