name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3fe54985b5e0e2027c4bc10ddf9c3f836a16cff0b011bd807ac6ed22a6c4870"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.173"

[options]
acceptable-game-versions = ["1.21.1"]
