name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b12a785b822b2fc848f777375a08cbb29b7c3281bd06a6b9a7769c0019d3f0b"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.173"

[options]
acceptable-game-versions = ["1.21.1"]
