name = "Forgeworks"
author = "Jaron Zijlstra"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c290675c3a6f47da500e83fede5f29d8dd88c800c52beb1714a336487fec331"

[versions]
fabric = "0.16.4"
minecraft = "1.21.1"
neoforge = "21.1.173"

[options]
acceptable-game-versions = ["1.21.1"]
