name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: false
      - name: Install Dependencies
        uses: ./.github/actions/install-yarn-dependencies
        with:
          node-version: 22
      - name: Run job
        run: yarn lint --fix=false

  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: false
      - name: Install Dependencies
        uses: ./.github/actions/install-yarn-dependencies
        with:
          node-version: 22
      - name: Run job
        run: yarn build

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: false
      - name: Install Dependencies
        uses: ./.github/actions/install-yarn-dependencies
        with:
          node-version: 22
      - name: Run job
        run: yarn test
